version: "3.8"

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - test_db

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: psql_user
      POSTGRES_PASSWORD: psql_password
    ports:
      - "5432:5432"

  test_db:
    image: postgres:latest
    container_name: test_postgres
    environment:
      POSTGRES_DB: test_postgres
      POSTGRES_USER: test_psql_user
      POSTGRES_PASSWORD: test_psql_password
    ports:
      - "5433:5432"
