version: "3.8"

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: psql_user
      POSTGRES_PASSWORD: psql_password
    ports:
      - "5432:5432"
